environment:
  name_prefix: dev
  aws_region: us-west-2

bastion:
  enabled: true
  instance_type: t3.micro
  volume_size: 30

network:
  vpc_cidr: 10.0.0.0/16
  public_subnet_1: 10.0.1.0/24
  private_subnet_1: 10.0.10.0/24

security:
  ssh_allowed_cidr:
    - 49.xx.xx.xx/32

eks:
  enabled: true
  cluster_name: dev-eks
  kubernetes_version: "1.29"

logging:
  cloudwatch_enabled: true

s3:
  log_bucket_enabled: true
